### ISSUE TITLE
CMISLib integration with Python 3

### ISSUE THREAD

**Issue by dsalvat** [jpotts/alfresco-api-python-examples#1]
Hi @jpotts,

I'm looking to upgrade the cmislib integration to python 3. Are there any plans for this? Is there any place I can look?

Thanks,

Daniel

**Comment by jpotts** [comment]
Yes, there has been some work done as part of the Apache Chemistry project
that Laurent Mignon has done, see his email below...

Jeff
----------
Dear community,

I'm pleased to announce that a new version of the python cmislib library is
now available into svn. (https://svn.apache.org/repos/asf/chemistry/cmislib
/branches/py3_compat/
<https://svn.apache.org/repos/asf/chemistry/cmislib/branches/py3_compat/>)
This version is a major evolution of this client
library to make it compatible at same time with python2 and python3.

The first step in the migration process was the implementation of a
continuous integration process based on travis and the refactoring of the
tests. (see #10 <https://github.com/apache/chemistry-cmislib/pull/10> for
the motivations) (All my devs are done into github and travis is freely
available into github)

In a second step, the code was modified syntactically to be both Python 2
and Python 3 compliant.

The httplib2 library was then replaced by python-request (
http://docs.python-requests.org/en/master/). It natively supports Python 2
and Python 3, manages sessions better (perfs are improved), has no problem
with large files and is very well maintained and documented. This library
seems to be a de facto standard.

Finally, the code is now flake8.

These changes constitute a major evolution of the library. Even if all the
unit tests allow us to believe that no regression was introduced by this
refactoring, these changes must be validated by an intensive use of the
library.
Comments and reviews are welcome.

Regards,

Laurent Mignon
